name: Tezster-CLI

on:
  push:
    branches:
      - master
      - tezster-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  ''

      - name: Fetch Package Version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Publish latest release
        run: npm publish
        if: "!contains(steps.package-version.outputs.version, 'beta')"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  
            
      - name: Publish beta release
        run: npm publish --tag beta
        if: contains(steps.package-version.outputs.version, 'beta')
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    