name: Tezster-CLI

on:
  push:
    branches:
      - master
      - tezster-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name:  'Version Bump'
        if: github.ref == 'refs/heads/master'
        uses:  'phips28/gh-action-bump-version@master'
        with:
          tag-prefix:  ''
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS_TOKEN }}

      - name: Fetch Package Version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Publish Latest Release
        if: "!contains(steps.package-version.outputs.version, 'beta') && github.ref == 'refs/heads/master'"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}  
            
      - name: Publish Beta Release
        if: contains(steps.package-version.outputs.version, 'beta') && github.ref == 'refs/heads/tezster-dev'
        run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    